# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: DroneGait
  dataset_root: /home/ub/DroneGait/silhouettes/cafp.bak
  dataset_partition: ./datasets/DroneGait/DroneGait.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: DroneGait

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 10000
  save_name: RGait3
  sampler:
    batch_size: 1
    sample_type: all_ordered
    type: InferenceSampler

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: RGait
  channels: [64, 128, 128]
  num_layers: 8
  num_head: 8
  dim_feedforward: 1024
  class_num: 21

optimizer_cfg:
  lr: 3.0e-4
  solver: Adam
  weight_decay: 5.0e-4

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 40000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: RGait3
  sync_BN: true
  total_iter: 50000
  sampler:
    batch_shuffle: true
    batch_size:
      - 4
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
